runners:
  cheap-x64-ubuntu24:
    family: ["m7i"]
    image: ubuntu24-full-x64
    spot: capacity-optimized
    ssh: false
    extras: ["s3-cache"]
    retry: true
    preinstall: |
      # Configure docker to use ipv6
      cat > /etc/docker/daemon.json <<EOF
      {
        "ipv6": true,
        "fixed-cidr-v6": "2001:db8:1::/64"
      }
      EOF
      systemctl restart docker

  fast-x64-ubuntu24:
    cpu: 32
    family: ["m7i-flex.8xlarge"]
    image: ubuntu24-full-x64
    spot: capacity-optimized
    extras: ["s3-cache"]
    ssh: false
    retry: true
    preinstall: |
      # Configure docker to use ipv6
      cat > /etc/docker/daemon.json <<EOF
      {
        "ipv6": true,
        "fixed-cidr-v6": "2001:db8:1::/64"
      }
      EOF
      systemctl restart docker


